name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main 

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r biometrics_toolbox/requirements.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build biometrics_toolbox/biometrics_toolbox
   
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GH_PAT2 }} # Use your PAT here
        publish_dir: biometrics_toolbox/biometrics_toolbox/_build/html


